DROP TABLE IF EXISTS book CASCADE;
DROP SEQUENCE IF EXISTS book_seq;

CREATE SEQUENCE book_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE book (
    id BIGINT PRIMARY KEY DEFAULT NEXTVAL('book_seq'),
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255),
    ISBN VARCHAR(50) UNIQUE NOT NULL,
    publication_date DATE,
    price NUMERIC(10,2),
    total INT NOT NULL DEFAULT 0,
    stock INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
